### ISSUE TITLE
Checklist to let people know about devel.unikernel.org

### ISSUE THREAD

**Issue by amirmc** [Unikernel-Systems/unikernel.org#27]
I should get in touch with various lists to let them know about devel.unikernel.org.  There's also feedback required on the new logo so that can be a new discussion topic too.
- [x] Add a comment to the 'why unikernel.org' topic about devel.unikernel.org
- [x] Push personal blog post live (about the logo - draft prepared)
- [x] Add a discussion topic for the logo
- [x] Switch on SSL for devel.unikernel.org (this will charge me)
- [x] Ask current people to go and register for the site
- [x] Merge the PR for [mirage.io](https://mirage.io) - https://github.com/mirage/mirage-www/pull/428
- [x] Check that the links actually work ;)
- [x] Make any known community members into moderators

Send messages to the following lists (draft already prepared):
- [x] MirageOS
- [x] HaLVM
- [x] Rump Kernel
- [x] IncludeOS (on their issue tracker)

(I'd send messages to others if they have lists).

Once the above is done, I'll close #25

**Comment by amirmc** [comment]
Making people moderators is an ongoing activity.
