### ISSUE TITLE
Checklist for 'releasing' the site

### ISSUE THREAD

**Issue by amirmc** [Unikernel-Systems/unikernel.org#7]
In rough order

- [x] Adjust DNS settings for unikernel.org
- [x] add introductory post (why this site exists)
- [x] add second post (about recent demo)
- [x] add link to this repo from the site
- [x] make YouTube video public
- [x] edit robots.txt
- [x] add `CNAME` file (this makes the site live)
- [x] make this repo public
- [x] write and post a tweet linking back to post
